name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Get dependencies
      run: |
        cd mobile_app
        flutter pub get
    
    - name: Build APK
      run: |
        cd mobile_app
        flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Build Debug APK
      run: |
        cd mobile_app
        flutter build apk --debug
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug